/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyAccountRouteImport } from './routes/verify-account'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedWorkspacesNewRouteImport } from './routes/_authenticated.workspaces.new'
import { Route as AuthenticatedWorkspacesWorkspaceIdRouteImport } from './routes/_authenticated.workspaces.$workspaceId'
import { Route as AuthenticatedWorkspacesWorkspaceIdCasesNewRouteImport } from './routes/_authenticated.workspaces.$workspaceId_.cases.new'
import { Route as AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRouteImport } from './routes/_authenticated.workspaces.$workspaceId_.cases.$caseId'

const VerifyAccountRoute = VerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesNewRoute =
  AuthenticatedWorkspacesNewRouteImport.update({
    id: '/workspaces/new',
    path: '/workspaces/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdRoute =
  AuthenticatedWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdCasesNewRoute =
  AuthenticatedWorkspacesWorkspaceIdCasesNewRouteImport.update({
    id: '/workspaces/$workspaceId_/cases/new',
    path: '/workspaces/$workspaceId/cases/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRoute =
  AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRouteImport.update({
    id: '/workspaces/$workspaceId_/cases/$caseId',
    path: '/workspaces/$workspaceId/cases/$caseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-account': typeof VerifyAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRoute
  '/workspaces/new': typeof AuthenticatedWorkspacesNewRoute
  '/workspaces/$workspaceId/cases/$caseId': typeof AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRoute
  '/workspaces/$workspaceId/cases/new': typeof AuthenticatedWorkspacesWorkspaceIdCasesNewRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-account': typeof VerifyAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRoute
  '/workspaces/new': typeof AuthenticatedWorkspacesNewRoute
  '/workspaces/$workspaceId/cases/$caseId': typeof AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRoute
  '/workspaces/$workspaceId/cases/new': typeof AuthenticatedWorkspacesWorkspaceIdCasesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-account': typeof VerifyAccountRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRoute
  '/_authenticated/workspaces/new': typeof AuthenticatedWorkspacesNewRoute
  '/_authenticated/workspaces/$workspaceId_/cases/$caseId': typeof AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRoute
  '/_authenticated/workspaces/$workspaceId_/cases/new': typeof AuthenticatedWorkspacesWorkspaceIdCasesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-account'
    | '/auth/callback'
    | '/workspaces/$workspaceId'
    | '/workspaces/new'
    | '/workspaces/$workspaceId/cases/$caseId'
    | '/workspaces/$workspaceId/cases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-account'
    | '/auth/callback'
    | '/'
    | '/workspaces/$workspaceId'
    | '/workspaces/new'
    | '/workspaces/$workspaceId/cases/$caseId'
    | '/workspaces/$workspaceId/cases/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-account'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/workspaces/new'
    | '/_authenticated/workspaces/$workspaceId_/cases/$caseId'
    | '/_authenticated/workspaces/$workspaceId_/cases/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyAccountRoute: typeof VerifyAccountRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-account': {
      id: '/verify-account'
      path: '/verify-account'
      fullPath: '/verify-account'
      preLoaderRoute: typeof VerifyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces/new': {
      id: '/_authenticated/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof AuthenticatedWorkspacesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId_/cases/new': {
      id: '/_authenticated/workspaces/$workspaceId_/cases/new'
      path: '/workspaces/$workspaceId/cases/new'
      fullPath: '/workspaces/$workspaceId/cases/new'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdCasesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId_/cases/$caseId': {
      id: '/_authenticated/workspaces/$workspaceId_/cases/$caseId'
      path: '/workspaces/$workspaceId/cases/$caseId'
      fullPath: '/workspaces/$workspaceId/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWorkspacesWorkspaceIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
  AuthenticatedWorkspacesNewRoute: typeof AuthenticatedWorkspacesNewRoute
  AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRoute
  AuthenticatedWorkspacesWorkspaceIdCasesNewRoute: typeof AuthenticatedWorkspacesWorkspaceIdCasesNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWorkspacesWorkspaceIdRoute:
    AuthenticatedWorkspacesWorkspaceIdRoute,
  AuthenticatedWorkspacesNewRoute: AuthenticatedWorkspacesNewRoute,
  AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRoute:
    AuthenticatedWorkspacesWorkspaceIdCasesCaseIdRoute,
  AuthenticatedWorkspacesWorkspaceIdCasesNewRoute:
    AuthenticatedWorkspacesWorkspaceIdCasesNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyAccountRoute: VerifyAccountRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
