// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// typegraphql-prisma currently declares Prisma 5 support, but generation works
// for this Prisma 6 schema. Keep the override scoped to Prisma commands.
process.env.SKIP_PRISMA_VERSION_CHECK ??= "true";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
