import type { CatalogProduct } from "./types";

export const catalog: CatalogProduct[] = [
  {
    tier: "SOLO",
    name: "Solo Workspace",
    description:
      "Essential case intelligence for solo operators managing active legal work in one focused workspace.",
    displayOrder: 10,
    selfService: true,
    priceLabel: "monthly_and_yearly",
    features: {
      includedMembers: 1,
      includedWorkspaces: 1,
      storageGb: 25,
      aiCreditsIncluded: 1500,
      teamCollaboration: false,
      rolesAndPermissions: false,
      sharedWorkspaces: false,
      auditLogs: false,
      ssoSaml: false,
      apiAccess: false,
      prioritySupport: "email",
      dedicatedOnboarding: false,
      additionalAiCredits: "purchase_packs",
      billingOwner: "workspace_owner",
    },
    marketingFeatures: [
      "One focused workspace, single seat",
      "1,500 AI credits included",
      "25 GB secure document storage",
      "Email support",
      "Additional AI credit packs available",
    ],
    prices: [
      {
        lookupKey: "solo_monthly",
        unitAmount: 9_900,
        currency: "usd",
        interval: "month",
        defaultForProduct: true,
        visibility: "public",
        effectiveMonthly: "99.00",
      },
      {
        lookupKey: "solo_yearly",
        unitAmount: 94_900,
        currency: "usd",
        interval: "year",
        visibility: "public",
        effectiveMonthly: "79.08",
      },
    ],
  },
  {
    tier: "PRO",
    name: "Pro Workspace",
    description:
      "Collaborative case intelligence for small teams that need shared workspaces, role-based access, and higher AI capacity.",
    displayOrder: 20,
    selfService: true,
    trialDays: 7,
    priceLabel: "monthly_and_yearly",
    features: {
      includedMembers: 10,
      includedWorkspaces: 10,
      storageGb: 100,
      aiCreditsIncluded: 5000,
      teamCollaboration: true,
      rolesAndPermissions: true,
      sharedWorkspaces: true,
      auditLogs: false,
      ssoSaml: false,
      apiAccess: "optional",
      prioritySupport: "priority",
      dedicatedOnboarding: false,
      additionalAiCredits: "purchase_packs",
      billingOwner: "workspace_owner",
    },
    marketingFeatures: [
      "Up to 10 members across 10 workspaces",
      "5,000 AI credits included",
      "100 GB secure document storage",
      "Shared workspaces with roles and permissions",
      "Priority support",
    ],
    prices: [
      {
        lookupKey: "pro_monthly",
        unitAmount: 29_900,
        currency: "usd",
        interval: "month",
        defaultForProduct: true,
        visibility: "public",
        effectiveMonthly: "299.00",
      },
      {
        lookupKey: "pro_yearly",
        unitAmount: 289_900,
        currency: "usd",
        interval: "year",
        visibility: "public",
        effectiveMonthly: "241.58",
      },
    ],
  },
  {
    tier: "ENTERPRISE",
    name: "Enterprise Workspace",
    description:
      "Custom case intelligence infrastructure for firms and organizations with advanced security, scale, onboarding, and support needs.",
    displayOrder: 30,
    selfService: false,
    startingAtMonthly: 1499,
    priceLabel: "contact_sales",
    features: {
      includedMembers: "unlimited",
      includedWorkspaces: "unlimited",
      storageGb: 500,
      storageExpandable: true,
      aiCreditsIncluded: 30000,
      aiCreditsCustom: true,
      teamCollaboration: true,
      rolesAndPermissions: "advanced",
      sharedWorkspaces: true,
      auditLogs: true,
      ssoSaml: true,
      apiAccess: true,
      prioritySupport: "dedicated",
      dedicatedOnboarding: true,
      additionalAiCredits: "negotiated",
      billingOwner: "organization",
    },
    marketingFeatures: [
      "Unlimited members and workspaces",
      "30,000+ AI credits with custom allocations",
      "500 GB expandable storage",
      "SSO/SAML, audit logs, and API access",
      "Dedicated support and onboarding",
    ],
    prices: [
      {
        lookupKey: "enterprise_monthly_internal",
        unitAmount: 149_900,
        currency: "usd",
        interval: "month",
        defaultForProduct: true,
        visibility: "hidden",
        effectiveMonthly: "1499.00",
        startingAt: "1499",
      },
      {
        lookupKey: "enterprise_yearly_internal",
        unitAmount: 1_439_900,
        currency: "usd",
        interval: "year",
        visibility: "hidden",
        effectiveMonthly: "1199.92",
        startingAt: "14399",
      },
    ],
  },
];
